version: "3.7"
services:
    tests:
        build:
            context: ..
            dockerfile: docker/Dockerfile.integration-tests
        image:
            localhost:5000/testsimg
        volumes:
            - ./output:/output-dir
        environment:
            - SERVER=http://node:3841
            - SCREENSHOT_DIR=/output-dir/screenshots
