name: Integration tests in Docker
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: run integration test
        run: docker-compose -p integ -f docker-compose.integration-tests.yml up --build --exit-code-from tests
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        working-directory: ./docker
      
      - name: upload screenshots
        uses: actions/upload-artifact@v1
        with:
          name: screenshots
          path: ./docker/output